// Exercise GIFs — URLs verified by fetching fitnessprogramer.com exercise pages
export const EXERCISE_GIFS: Record<string, string> = {
  // ── Original exercises ─────────────────────────────────────────────────────
  squat:            'https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif',
  pushup:           'https://fitnessprogramer.com/wp-content/uploads/2021/02/Push-Up.gif',
  benchpress:       'https://gymvisual.com/img/p/1/7/5/5/2/17552.gif',
  chestpress:       'https://fitnessprogramer.com/wp-content/uploads/2021/12/One-Arm-Cable-Chest-Press.gif',
  lunge:            'https://fitnessprogramer.com/wp-content/uploads/2023/07/bodyweight-lunges.gif',
  sidelunge:        'https://fitnessprogramer.com/wp-content/uploads/2021/05/Side-Lunge-Stretch.gif',
  deadlift:         'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif',
  shoulderpress:    'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif',
  curlup:           'https://fitnessprogramer.com/wp-content/uploads/2015/11/Crunch.gif',
  situp:            'https://gymvisual.com/img/p/5/4/5/9/5459.gif',
  bicepcurl:        'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif',
  jumpingjack:      'https://fitnessprogramer.com/wp-content/uploads/2021/05/Jumping-jack.gif',
  highnees:         'https://fitnessprogramer.com/wp-content/uploads/2021/08/High-Knee-Run.gif',
  mountainclimber:  'https://fitnessprogramer.com/wp-content/uploads/2021/02/Mountain-climber.gif',
  buttskick:        'https://fitnessprogramer.com/wp-content/uploads/2021/10/Butt-Kicks.gif',
  calfraise:        'https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif',
  hipcircle:        'https://fitnessprogramer.com/wp-content/uploads/2021/01/hip-circles.gif',
  plank:            'https://fitnessprogramer.com/wp-content/uploads/2021/02/plank.gif',
  wallsit:          'https://gymvisual.com/img/p/9/0/5/3/9053.gif',
  tricepextension:  'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Triceps-Extension.gif',
  lateralraise:     'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif',
  hammercurl:       'https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif',
  pullup:           'https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif',
  armcircle:        'https://fitnessprogramer.com/wp-content/uploads/2021/07/Arm-Circles_Shoulders.gif',
  scapulasqueeze:   'https://fitnessprogramer.com/wp-content/uploads/2021/06/Band-pull-apart.gif',
  crossbodystretch: 'https://fitnessprogramer.com/wp-content/uploads/2021/04/Across-Chest-Shoulder-Stretch.gif',
  tricepstretch:    'https://gymvisual.com/img/p/5/5/4/0/5540.gif',
  chestfly:         'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif',
  jumpsquat:        'https://fitnessprogramer.com/wp-content/uploads/2021/02/Jump-Squat.gif',
  burpee:           'https://fitnessprogramer.com/wp-content/uploads/2021/02/burpees.gif',
  // ── New exercises — all URLs verified from fitnessprogramer.com pages ──────
  // Push variations
  diamondpushup:          'https://fitnessprogramer.com/wp-content/uploads/2021/02/Diamond-Push-up.gif',
  widegripushup:          'https://fitnessprogramer.com/wp-content/uploads/2021/06/Wide-Push-Up.gif',
  declinepushup:          'https://fitnessprogramer.com/wp-content/uploads/2015/07/Decline-Push-Up.gif',
  inclinepushup:          'https://fitnessprogramer.com/wp-content/uploads/2021/06/Incline-Push-Up.gif',
  pikeupshup:             'https://fitnessprogramer.com/wp-content/uploads/2021/06/Pike-Push-up.gif',
  // Pull / back
  chinup:                 'https://fitnessprogramer.com/wp-content/uploads/2021/03/Chin-Up.gif',
  invertedrow:            'https://fitnessprogramer.com/wp-content/uploads/2021/06/Inverted-Row.gif',
  dumbbellrow:            'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif',
  superman:               'https://fitnessprogramer.com/wp-content/uploads/2021/02/Superman-exercise.gif',
  // Lower body
  bulgariansplitsquat:    'https://fitnessprogramer.com/wp-content/uploads/2022/02/Bodyweight-Bulgarian-Split-Squat.gif',
  glutebridge:            'https://fitnessprogramer.com/wp-content/uploads/2021/02/Glute-Bridge-.gif',
  hipthrust:              'https://fitnessprogramer.com/wp-content/uploads/2021/02/barbell-hip-thrust.gif',
  donkeykick:             'https://fitnessprogramer.com/wp-content/uploads/2021/02/Donkey-Kicks.gif',
  firehydrant:            'https://fitnessprogramer.com/wp-content/uploads/2021/02/Fire-Hydrant.gif',
  reverseLunge:           'https://fitnessprogramer.com/wp-content/uploads/2022/08/bodyweight-reverse-lunge.gif',
  curtsylunge:            'https://fitnessprogramer.com/wp-content/uploads/2023/09/curtsy-lunge.gif',
  sumoSquat:              'https://fitnessprogramer.com/wp-content/uploads/2021/02/BODYWEIGHT-SUMO-SQUAT.gif',
  stepup:                 'https://fitnessprogramer.com/wp-content/uploads/2021/09/Step-Up.gif',
  nordicCurl:             'https://fitnessprogramer.com/wp-content/uploads/2021/06/Nordic-Hamstring-Curl.gif',
  // Core
  sideplank:              'https://fitnessprogramer.com/wp-content/uploads/2021/06/Side-Plank.gif',
  deadbug:                'https://fitnessprogramer.com/wp-content/uploads/2021/05/Dead-Bug.gif',
  birddog:                'https://fitnessprogramer.com/wp-content/uploads/2022/07/Bird-Dog.gif',
  russiantwist:           'https://fitnessprogramer.com/wp-content/uploads/2021/02/Russian-Twist.gif',
  bicycleCrunch:          'https://fitnessprogramer.com/wp-content/uploads/2021/02/Bicycle-Crunch.gif',
  legRaise:               'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lying-Leg-Raise.gif',
  flutterKick:            'https://fitnessprogramer.com/wp-content/uploads/2022/02/Seated-Flutter-Kick.gif',
  hollowbody:             'https://fitnessprogramer.com/wp-content/uploads/2021/06/Hollow-Body-Hold.gif',
  vSit:                   'https://fitnessprogramer.com/wp-content/uploads/2021/06/V-Sit.gif',
  abWheel:                'https://fitnessprogramer.com/wp-content/uploads/2021/06/Ab-Wheel-Rollout.gif',
  // Cardio / plyometric
  boxjump:                'https://fitnessprogramer.com/wp-content/uploads/2021/06/Box-Jump.gif',
  skaterjump:             'https://fitnessprogramer.com/wp-content/uploads/2021/09/Skater-Jump.gif',
  tuckjump:               'https://fitnessprogramer.com/wp-content/uploads/2021/09/Tuck-Jump.gif',
  starjump:               'https://fitnessprogramer.com/wp-content/uploads/2021/06/Star-Jump.gif',
  broadjump:              'https://fitnessprogramer.com/wp-content/uploads/2021/09/Broad-Jump.gif',
  shadowboxing:           'https://fitnessprogramer.com/wp-content/uploads/2023/09/shadow-boxing-workout.gif',
  // Mobility / stretches
  catcow:                 'https://fitnessprogramer.com/wp-content/uploads/2021/02/cat-cow.gif',
  childpose:              'https://fitnessprogramer.com/wp-content/uploads/2021/04/Childs-Pose.gif',
  worldsgreateststretch:  'https://fitnessprogramer.com/wp-content/uploads/2022/01/Worlds-Greatest-Stretch.gif',
  hipflexorstretch:       'https://fitnessprogramer.com/wp-content/uploads/2021/08/Kneeling-Hip-Flexor-Stretch.gif',
  hamstringstretch:       'https://fitnessprogramer.com/wp-content/uploads/2021/05/Standing-Hamstring-Stretch.gif',
  quadstretch:            'https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Quad-Stretch.gif',
  pigeonpose:             'https://fitnessprogramer.com/wp-content/uploads/2021/06/Pigeon-Pose.gif',
  downdogstretch:         'https://fitnessprogramer.com/wp-content/uploads/2021/04/Downward-Dog-Stretch.gif',
  cobrapose:              'https://fitnessprogramer.com/wp-content/uploads/2021/04/Cobra-Stretch.gif',
  seatedspinaltwist:      'https://fitnessprogramer.com/wp-content/uploads/2021/06/Seated-Spinal-Twist.gif',
  anklecircle:            'https://fitnessprogramer.com/wp-content/uploads/2021/09/Ankle-Circles.gif',
  neckroll:               'https://fitnessprogramer.com/wp-content/uploads/2021/04/Neck-Circles.gif',
  shoulderroll:           'https://fitnessprogramer.com/wp-content/uploads/2021/07/Shoulder-Rolls.gif',
  wristcircle:            'https://fitnessprogramer.com/wp-content/uploads/2021/09/Wrist-Circles.gif',
  // Dumbbell strength
  gobletSquat:            'https://fitnessprogramer.com/wp-content/uploads/2023/01/Dumbbell-Goblet-Squat.gif',
  romaniandeadlift:       'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Romanian-Deadlift.gif',
  arnoldpress:            'https://fitnessprogramer.com/wp-content/uploads/2021/02/Arnold-Press.gif',
  frontraise:             'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Front-Raise.gif',
  reverseFly:             'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Reverse-Fly.gif',
  skullcrusher:           'https://fitnessprogramer.com/wp-content/uploads/2021/06/Dumbbell-Skull-Crusher.gif',
  concentrationcurl:      'https://fitnessprogramer.com/wp-content/uploads/2021/02/Concentration-Curl.gif',
  zottmancurl:            'https://fitnessprogramer.com/wp-content/uploads/2021/04/zottman-curl.gif',
  wristcurl:              'https://fitnessprogramer.com/wp-content/uploads/2021/02/barbell-Wrist-Curl.gif',
  goodmorning:            'https://fitnessprogramer.com/wp-content/uploads/2021/09/Good-Morning-Exercise.gif',
  hyperextension:         'https://fitnessprogramer.com/wp-content/uploads/2021/04/Hyperextensions.gif',
}
