export interface ExerciseInfo {
  id: string
  name: string
  muscles: string[]
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
  description: string
  cues: string[]
  riskNote: string
  isHold?: boolean
  isNew?: boolean
}

export const EXERCISE_INFO: ExerciseInfo[] = [
  {
    id: 'squat',
    name: 'Squat',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
    difficulty: 'Beginner',
    description: 'The foundational lower-body movement. Builds strength through the full leg chain and improves hip mobility.',
    cues: [
      'Feet shoulder-width apart, toes slightly out',
      'Keep chest tall throughout the movement',
      'Drive knees out — track over your middle toe',
      'Descend until thighs are parallel to the floor',
      'Drive through your whole foot on the way up',
    ],
    riskNote: 'Main risk: knee valgus (knees caving inward). The AI tracks this in real time.',
  },
  {
    id: 'pushup',
    name: 'Push-Up',
    muscles: ['Chest', 'Triceps', 'Shoulders', 'Core'],
    difficulty: 'Beginner',
    description: 'A compound upper-body push movement. Trains chest, shoulders, and triceps while demanding core stability.',
    cues: [
      'Hands slightly wider than shoulder-width',
      'Body forms a straight line from head to heel',
      'Lower until chest almost touches the floor',
      'Elbows at ~45° from your torso — not flared wide',
      'Squeeze glutes and core throughout',
    ],
    riskNote: 'Main risks: hip sag (weak core) and elbow flare (shoulder strain). Both are tracked live.',
  },
  {
    id: 'lunge',
    name: 'Lunge',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Calves'],
    difficulty: 'Beginner',
    description: 'A unilateral leg exercise that builds balance, coordination, and single-leg strength.',
    cues: [
      'Step forward long enough that your shin stays vertical',
      'Keep your torso upright — don\'t lean forward',
      'Front knee tracks over your second toe',
      'Lower your back knee toward (not onto) the floor',
      'Push through your front heel to return',
    ],
    riskNote: 'Main risk: front knee driving past the toes. The AI monitors knee tracking in real time.',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    muscles: ['Hamstrings', 'Glutes', 'Lower Back', 'Traps', 'Core'],
    difficulty: 'Intermediate',
    description: 'The ultimate posterior-chain exercise. Builds total-body strength but demands proper spinal position.',
    cues: [
      'Hip-width stance, bar over mid-foot',
      'Hinge at the hips — push them back first',
      'Keep the bar close to your body throughout',
      'Neutral spine: no rounding at the lower back',
      'Drive your feet into the floor and lock out at the top',
    ],
    riskNote: 'Highest injury risk of all exercises: spinal rounding. AI scoring is more aggressive for deadlifts.',
  },
  {
    id: 'mountainclimber',
    name: 'Mountain Climbers',
    muscles: ['Core', 'Hip Flexors', 'Shoulders', 'Quads'],
    difficulty: 'Intermediate',
    description: 'A dynamic plank variation that combines core stability with cardio. Alternating knee drives build endurance and hip flexor strength.',
    cues: [
      'Start in a high plank — shoulders directly over wrists',
      'Keep hips level — no piking up or sagging down',
      'Drive one knee toward your chest, then quickly switch',
      'Keep your core braced throughout — belly button to spine',
      'Land lightly on the ball of each foot',
    ],
    riskNote: 'Main risk: hip piking or sagging as you fatigue. The AI monitors your hip position against the shoulder–ankle line.',
  },
  {
    id: 'benchpress',
    name: 'Bench Press',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'The primary horizontal push movement. Builds chest mass and upper-body pressing strength.',
    cues: [
      'Retract and depress your shoulder blades — pack them into the bench',
      'Grip just outside shoulder-width, wrists stacked over elbows',
      'Lower the bar to your lower chest in a slight arc',
      'Elbows at ~45-75° from your torso — not flared wide',
      'Press back up and slightly toward your face at lockout',
    ],
    riskNote: 'Main risk: elbow flare past shoulder width — high shoulder impingement risk. AI tracks elbow path and wrist symmetry.',
  },
  {
    id: 'shoulderpress',
    name: 'Shoulder Press',
    muscles: ['Shoulders', 'Triceps', 'Upper Traps'],
    difficulty: 'Intermediate',
    description: 'An overhead pressing movement that builds shoulder strength and stability.',
    cues: [
      'Start with hands at shoulder height, elbows slightly in front',
      'Press directly overhead until arms are fully extended',
      'Keep your wrists stacked over your elbows',
      'Don\'t arch your lower back — brace your core',
      'Lower with control — don\'t drop the weight',
    ],
    riskNote: 'Main risks: lower back arch and wrist/shoulder asymmetry. Both tracked by pose landmarks.',
  },
  {
    id: 'curlup',
    name: 'Curl-Up',
    muscles: ['Abs', 'Hip Flexors'],
    difficulty: 'Beginner',
    description: 'A spinal-flexion core exercise that targets the rectus abdominis with low lumbar stress.',
    cues: [
      'Lie flat, knees bent, feet on the floor',
      'Place hands behind your head without pulling your neck',
      'Curl your shoulder blades off the floor — don\'t sit up fully',
      'Exhale on the way up, inhale on the way down',
      'Keep your lower back pressed into the floor',
    ],
    riskNote: 'Main risk: neck strain from pulling the head forward. The AI watches shoulder symmetry.',
  },
  {
    id: 'bicepcurl',
    name: 'Bicep Curl',
    muscles: ['Biceps', 'Brachialis', 'Forearms'],
    difficulty: 'Beginner',
    description: 'An isolation exercise for the elbow flexors. Simple but often cheated with body momentum.',
    cues: [
      'Stand tall — no swinging your torso',
      'Keep elbows pinned to your sides throughout',
      'Curl until your forearms are vertical',
      'Lower slowly — 2-3 second descent',
      'Squeeze at the top of each rep',
    ],
    riskNote: 'Main risks: elbow drift and body sway. The AI catches momentum cheating via shoulder position.',
  },
  {
    id: 'jumpingjack',
    name: 'Jumping Jack',
    muscles: ['Full Body', 'Cardio'],
    difficulty: 'Beginner',
    description: 'A full-body cardio movement that elevates heart rate and warms up the whole body.',
    cues: [
      'Start feet together, arms at your sides',
      'Jump feet wide while raising arms overhead',
      'Return to start in one fluid motion',
      'Land softly — bend your knees slightly',
      'Keep a steady rhythm — aim for 60-80 per minute',
    ],
    riskNote: 'Low injury risk. The AI watches arm symmetry to ensure full range of motion.',
  },
  {
    id: 'highnees',
    name: 'High Knees',
    muscles: ['Hip Flexors', 'Quads', 'Core', 'Cardio'],
    difficulty: 'Beginner',
    description: 'A high-intensity cardio drill that drives knee lift and builds hip flexor power.',
    cues: [
      'Run in place, driving knees up to hip height',
      'Stay on the balls of your feet',
      'Pump your arms to maintain rhythm',
      'Keep your torso upright — don\'t lean back',
      'Aim for speed: 80-100 contacts per minute',
    ],
    riskNote: 'The AI monitors torso sway, which indicates fatigue or loss of form at high speeds.',
  },
  {
    id: 'plank',
    name: 'Plank',
    muscles: ['Core', 'Shoulders', 'Glutes'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'An isometric core hold that builds anti-extension strength and full-body stability.',
    cues: [
      'Forearms flat, elbows under shoulders',
      'Body forms a rigid straight line head to heel',
      'Squeeze glutes and quads hard',
      'Don\'t let your hips sag or pike up',
      'Breathe steadily — don\'t hold your breath',
    ],
    riskNote: 'Main risk: hip sag (core weakness). Same alignment check as push-up.',
  },
  {
    id: 'wallsit',
    name: 'Wall Sit',
    muscles: ['Quads', 'Glutes', 'Calves'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'An isometric lower-body hold that builds quad endurance and knee stability.',
    cues: [
      'Back flat against the wall',
      'Thighs parallel to the floor (90° knee angle)',
      'Feet shoulder-width, flat on the floor',
      'Keep knees tracking over your toes',
      'Arms at your sides or on your thighs — not pushing off',
    ],
    riskNote: 'Main risk: knee valgus under fatigue. Same tracking as squats.',
  },
  {
    id: 'tricepextension',
    name: 'Tricep Extension',
    muscles: ['Triceps', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'An overhead isolation exercise that fully stretches and contracts the triceps through a long range of motion.',
    cues: [
      'Stand tall, core braced, feet shoulder-width',
      'Raise both arms overhead, elbows pointing forward',
      'Lower the weight behind your head by bending at the elbows only',
      'Keep elbows close together — don\'t let them flare wide',
      'Press back to full extension, squeezing the triceps at the top',
    ],
    riskNote: 'Main risks: elbow flare and upper arm drift. The AI tracks elbow position relative to your shoulders.',
  },
  {
    id: 'lateralraise',
    name: 'Lateral Raise',
    muscles: ['Shoulders', 'Traps', 'Serratus'],
    difficulty: 'Beginner',
    description: 'An isolation exercise for the lateral deltoid that builds shoulder width. Commonly cheated with momentum.',
    cues: [
      'Stand tall, slight bend in the elbows — don\'t lock them straight',
      'Raise arms out to the sides until parallel with the floor',
      'Lead with your elbows, not your wrists',
      'Lower slowly — 2-3 second descent',
      'No shrugging — keep your traps relaxed',
    ],
    riskNote: 'Main risks: asymmetric arm height and forward wrist reach. The AI tracks wrist symmetry and position.',
  },
  {
    id: 'hammercurl',
    name: 'Hammer Curl',
    muscles: ['Biceps', 'Brachialis', 'Brachioradialis', 'Forearms'],
    difficulty: 'Beginner',
    description: 'A neutral-grip curl variation that hits the brachialis and brachioradialis harder than a standard curl.',
    cues: [
      'Palms facing each other (neutral grip) throughout the movement',
      'Keep elbows pinned to your sides — no swinging',
      'Curl until forearms are vertical',
      'Lower with control — 2 second descent',
      'Don\'t rotate your wrists — maintain neutral grip the entire rep',
    ],
    riskNote: 'Same risks as bicep curl: elbow drift and body sway. The AI catches momentum cheating.',
  },
  {
    id: 'pullup',
    name: 'Pull-Up',
    muscles: ['Lats', 'Biceps', 'Rear Delts', 'Core'],
    difficulty: 'Advanced',
    description: 'The gold-standard back exercise. Requires pulling your bodyweight from a dead hang to chin-over-bar.',
    cues: [
      'Start from a full dead hang — arms completely extended',
      'Pull your shoulder blades down and together before initiating',
      'Drive elbows toward your hips as you pull',
      'Chin clears the bar — don\'t stop short',
      'Lower with control — avoid dropping into the dead hang',
    ],
    riskNote: 'Main risks: shoulder asymmetry and elbow flare. The AI tracks shoulder balance and elbow alignment.',
  },
  {
    id: 'buttskick',
    name: 'Butt Kicks',
    muscles: ['Hamstrings', 'Glutes', 'Calves', 'Cardio'],
    difficulty: 'Beginner',
    description: 'A high-cadence cardio drill that fires the hamstrings and warms up the posterior chain.',
    cues: [
      'Run in place, kicking your heels up toward your glutes',
      'Stay on the balls of your feet — light and quick',
      'Keep your torso upright — slight forward lean, not leaning back',
      'Pump your arms in opposition to your legs',
      'Aim for speed: 80-100 contacts per minute',
    ],
    riskNote: 'Low injury risk. AI monitors torso lean — leaning back stresses the lower back.',
  },
  {
    id: 'calfraise',
    name: 'Calf Raises',
    muscles: ['Gastrocnemius', 'Soleus', 'Calves'],
    difficulty: 'Beginner',
    description: 'An isolation exercise for the calves. Simple but often done with too little range of motion.',
    cues: [
      'Stand with feet hip-width, toes pointing forward',
      'Rise all the way onto the balls of your feet — full extension',
      'Hold the top for 1 second — squeeze the calves',
      'Lower with control — 2-3 second descent',
      'Keep weight evenly distributed across both feet',
    ],
    riskNote: 'Very low injury risk. AI watches for uneven loading and incomplete range of motion.',
  },
  {
    id: 'situp',
    name: 'Sit-Up',
    muscles: ['Abs', 'Hip Flexors', 'Core'],
    difficulty: 'Beginner',
    description: 'A full spinal-flexion core exercise that brings the torso to an upright position.',
    cues: [
      'Lie flat, knees bent, feet on the floor or anchored',
      'Cross arms on chest or place hands behind head without pulling',
      'Curl up until your torso is nearly vertical',
      'Exhale on the way up, inhale on the way down',
      'Lower with control — don\'t flop back down',
    ],
    riskNote: 'Main risk: neck strain from pulling the head forward. Keep hands light on the head.',
  },
  {
    id: 'armcircle',
    name: 'Arm Circles',
    muscles: ['Shoulders', 'Rotator Cuff', 'Upper Back'],
    difficulty: 'Beginner',
    description: 'A shoulder mobility warm-up or active recovery exercise. Lubricates the joint through full rotation.',
    cues: [
      'Stand tall, arms extended straight out to the sides',
      'Make full circles — as big as possible',
      'Keep your core tight — don\'t let your torso rotate',
      'Do both directions: forward and backward sets',
      'Breathe steadily — this should feel like a stretch, not a strain',
    ],
    riskNote: 'Very low injury risk. AI checks arm symmetry and full range of motion on both sides.',
  },
  {
    id: 'hipcircle',
    name: 'Hip Circles',
    muscles: ['Hip Flexors', 'Glutes', 'Lower Back', 'Core'],
    difficulty: 'Beginner',
    description: 'A dynamic mobility drill that lubricates the hip joint and loosens the lower back. Essential warm-up movement.',
    cues: [
      'Stand with feet shoulder-width, hands on hips',
      'Rotate your hips in the widest circle possible',
      'Keep your shoulders still — only your hips move',
      'Go slow: 3–4 seconds per circle',
      'Do equal reps in both directions',
    ],
    riskNote: 'Very low injury risk. AI watches for shoulder sway — only the hips should be driving the movement.',
  },
  {
    id: 'chestpress',
    name: 'Chest Press',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    difficulty: 'Beginner',
    description: 'A standing horizontal push movement. Mimics the bench press pattern but upright — great for activation with bands or light weights.',
    cues: [
      'Start with hands at chest height, elbows at shoulder level',
      'Press both arms forward until nearly straight',
      'Keep wrists neutral — do not bend them back',
      'Return with control — don\'t let the weight snap your elbows back',
      'Keep torso upright throughout — no rocking or swaying',
    ],
    riskNote: 'Low injury risk. AI monitors elbow height symmetry and torso stability.',
  },
  {
    id: 'crossbodystretch',
    name: 'Cross-Body Shoulder Stretch',
    muscles: ['Posterior Deltoid', 'Rotator Cuff', 'Upper Back'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'A static stretch for the rear shoulder and upper back. Commonly used in warm-up and cooldown routines.',
    cues: [
      'Bring one arm straight across your chest at shoulder height',
      'Use the opposite hand to hold it at the elbow — not the wrist',
      'Keep your shoulder down — don\'t let it shrug up toward your ear',
      'Hold for 20–30 seconds, then switch sides',
      'Look straight ahead — don\'t rotate your torso toward the arm',
    ],
    riskNote: 'Very low injury risk. AI watches for shoulder hike and torso rotation.',
  },
  {
    id: 'tricepstretch',
    name: 'Tricep Stretch',
    muscles: ['Triceps', 'Shoulder', 'Lats'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'An overhead stretch for the tricep and shoulder. Improves elbow extension mobility.',
    cues: [
      'Raise one arm overhead and bend the elbow, dropping your hand behind your head',
      'Use the other hand to gently press down on the bent elbow',
      'Keep the elbow pointing straight up — not forward or out to the side',
      'Stay upright — don\'t lean sideways to compensate',
      'Hold for 20–30 seconds, then switch arms',
    ],
    riskNote: 'Very low injury risk. AI checks elbow alignment and neck neutrality.',
  },
  {
    id: 'scapulasqueeze',
    name: 'Scapula Squeeze',
    muscles: ['Rhomboids', 'Middle Trapezius', 'Rear Deltoids'],
    difficulty: 'Beginner',
    description: 'An upper-back corrective exercise that retracts the shoulder blades. Counters forward posture from sitting and pressing work.',
    cues: [
      'Stand or sit tall — do not let your chest collapse',
      'Pull your shoulder blades toward each other as if pinching a pencil between them',
      'Keep your shoulders DOWN — do not shrug up toward your ears',
      'Hold the squeeze for 2–3 seconds, then release fully',
      'Arms can be at your sides, in a "T", or bent in a "W" — all are valid',
    ],
    riskNote: 'Very low injury risk. Main error is shrugging instead of retracting. AI tracks shoulder symmetry and height.',
  },
  {
    id: 'sidelunge',
    name: 'Side Lunge',
    muscles: ['Glutes', 'Quads', 'Adductors', 'Hamstrings'],
    difficulty: 'Beginner',
    description: 'A lateral lunge that trains the frontal plane — often neglected. Builds hip mobility, adductor strength, and single-leg stability.',
    cues: [
      'Step wide enough that your shin stays vertical — knee not past toes',
      'Push your hips back and sit into the bending leg',
      'Keep the extended leg straight, foot flat on the floor',
      'Torso upright — do not lean forward over your knee',
      'Drive through your heel to return to standing',
    ],
    riskNote: 'Main risk: knee valgus on the bending side. AI monitors lateral knee tracking in real time.',
  },
  {
    id: 'chestfly',
    name: 'Chest Fly',
    muscles: ['Chest', 'Anterior Deltoid', 'Biceps (stabilizer)'],
    difficulty: 'Intermediate',
    description: 'An isolation movement that stretches and contracts the pectorals through a wide arc. Best done with cables or light dumbbells.',
    cues: [
      'Slight bend in the elbows — maintain throughout the movement',
      'Open arms wide in a controlled arc until you feel a chest stretch',
      'Keep wrists neutral — do not let them bend back',
      'Squeeze the chest as arms return to center — do not slam them together',
      'Keep shoulder blades pinched back and down throughout',
    ],
    riskNote: 'Main risk: going too wide with straight elbows — tears the pec tendon. AI monitors arm symmetry and elbow position.',
  },
  {
    id: 'jumpsquat',
    name: 'Jump Squat',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Calves', 'Core'],
    difficulty: 'Intermediate',
    description: 'An explosive lower-body movement that builds power and elevates heart rate. The squat pattern meets plyometric training.',
    cues: [
      'Squat to at least parallel before driving up',
      'Explode through your whole foot — drive the floor away',
      'Land softly — bend your knees and hips to absorb the impact',
      'Keep knees tracking over your toes on both the squat and the landing',
      'Maintain an upright chest throughout — do not collapse forward',
    ],
    riskNote: 'Main risk: knee valgus on landing — high ACL injury risk. The AI watches landing mechanics closely.',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    muscles: ['Full Body', 'Cardio', 'Core', 'Chest', 'Quads', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'The ultimate full-body conditioning exercise. Three phases — squat, plank, and jump — in one continuous movement.',
    cues: [
      'Phase 1 — Stand: feet shoulder-width, ready to drop',
      'Phase 2 — Squat & plank: hands hit the floor, jump/step feet back to plank position — hips stay level',
      'Phase 3 — Return & jump: jump/step feet forward, drive through your legs, jump and clap overhead',
      'Keep your core braced in the plank — no hip sagging or piking',
      'Land softly each time — absorb impact through bent knees',
    ],
    riskNote: 'Key risks: hip sag in plank phase and knee valgus on landing. Both tracked in real time.',
  },

  // ── Bodyweight Upper ───────────────────────────────────────────────────

  {
    id: 'diamondpushup',
    name: 'Diamond Push-Up',
    muscles: ['Triceps', 'Chest', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'A close-grip push-up variation that shifts the load heavily onto the triceps and inner chest.',
    cues: [
      'Form a diamond shape with your thumbs and index fingers under your chest',
      'Keep elbows tracking close to your sides — they should skim your ribcage',
      'Lower chest to your hands, then press back up',
      'Keep hips level — same alignment as a standard push-up',
      'If wrists are uncomfortable, use push-up handles or make fists',
    ],
    riskNote: 'Higher elbow stress than standard push-ups. AI monitors elbow flare and wrist alignment.',
    isNew: true,
  },
  {
    id: 'widegripushup',
    name: 'Wide-Grip Push-Up',
    muscles: ['Chest', 'Anterior Deltoid', 'Triceps'],
    difficulty: 'Beginner',
    description: 'A wider push-up stance that emphasizes the outer pectoral. More chest activation, less tricep.',
    cues: [
      'Place hands 1.5–2x shoulder width apart',
      'Elbows travel out to roughly 75° from your torso',
      'Lower chest to floor in a straight line — no diagonal drift',
      'Maintain rigid body position from head to heel',
      'Squeeze chest at the top of each rep',
    ],
    riskNote: 'Wide elbow angle increases shoulder stress. AI tracks elbow angle and shoulder symmetry.',
    isNew: true,
  },
  {
    id: 'declinepushup',
    name: 'Decline Push-Up',
    muscles: ['Upper Chest', 'Shoulders', 'Triceps'],
    difficulty: 'Intermediate',
    description: 'Elevating the feet shifts emphasis to the upper chest and anterior delts — the hardest push-up variation.',
    cues: [
      'Place feet on a chair or bench, hands on the floor at shoulder width',
      'Body forms a straight angled line from head to heel',
      'Lower chest toward the floor — keep elbows at 45°',
      'Press back to full arm extension without locking elbows',
      'Core braced — prevent hips from sagging',
    ],
    riskNote: 'Increased shoulder demand. Ensure shoulder blade retraction before each rep. AI monitors shoulder symmetry.',
    isNew: true,
  },
  {
    id: 'inclinepushup',
    name: 'Incline Push-Up',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    difficulty: 'Beginner',
    description: 'Hands on an elevated surface (bench, wall) reduces body weight load. The best push-up regression.',
    cues: [
      'Place hands on a stable elevated surface — bench, step, or wall',
      'Lean in at an angle, forming a straight body line',
      'Lower chest to the surface, then press back',
      'The lower the incline, the harder the movement',
      'Use this to build toward full push-ups',
    ],
    riskNote: 'Lower injury risk than standard push-up. Great entry-level pressing pattern. AI checks body alignment.',
    isNew: true,
  },
  {
    id: 'pikeupshup',
    name: 'Pike Push-Up',
    muscles: ['Shoulders', 'Triceps', 'Upper Chest'],
    difficulty: 'Intermediate',
    description: 'A push-up from an inverted V position that mimics an overhead press. A handstand press progression.',
    cues: [
      'Start in downward dog — hips high, forming an inverted V',
      'Lower your head toward the floor between your hands',
      'Press back up — drive through the shoulders, not the chest',
      'The more vertical your torso, the more it becomes a handstand push-up',
      'Keep legs straight and core engaged throughout',
    ],
    riskNote: 'Significant shoulder demand. AI monitors head path and elbow symmetry.',
    isNew: true,
  },
  {
    id: 'chinup',
    name: 'Chin-Up',
    muscles: ['Biceps', 'Lats', 'Core', 'Rear Delts'],
    difficulty: 'Advanced',
    description: 'A supinated-grip pull-up. Greater bicep activation than a pull-up, slightly less lat emphasis.',
    cues: [
      'Grip the bar with palms facing you, shoulder-width',
      'Start from a full dead hang — arms fully extended',
      'Pull until chin clears the bar, driving elbows toward the floor',
      'Squeeze your biceps and lats hard at the top',
      'Lower slowly — 3-second eccentric for maximum strength gains',
    ],
    riskNote: 'AI tracks shoulder symmetry and elbow alignment on each rep.',
    isNew: true,
  },
  {
    id: 'invertedrow',
    name: 'Inverted Row',
    muscles: ['Lats', 'Rhomboids', 'Rear Delts', 'Biceps', 'Core'],
    difficulty: 'Beginner',
    description: 'A horizontal pulling movement using a low bar or table. The bodyweight row — perfect for back strength.',
    cues: [
      'Hang below a bar or table, body in a straight line from head to heel',
      'Pull your chest to the bar, driving elbows back behind you',
      'Squeeze shoulder blades together at the top',
      'Lower with full arm extension — don\'t cut the range short',
      'The more horizontal your body, the harder the movement',
    ],
    riskNote: 'Low injury risk. AI monitors scapular retraction and body alignment.',
    isNew: true,
  },
  {
    id: 'superman',
    name: 'Superman',
    muscles: ['Lower Back', 'Glutes', 'Hamstrings', 'Rear Delts'],
    difficulty: 'Beginner',
    description: 'A prone back extension that strengthens the posterior chain without any load. Essential lower back health exercise.',
    cues: [
      'Lie face down, arms extended overhead',
      'Simultaneously lift your arms, chest, and legs off the floor',
      'Squeeze glutes hard at the top — this protects the lower back',
      'Hold for 2-3 seconds at peak, then lower with control',
      'Keep your neck neutral — look at the floor, not forward',
    ],
    riskNote: 'Very low injury risk. AI monitors symmetry of arm and leg lift.',
    isNew: true,
  },

  // ── Bodyweight Lower ───────────────────────────────────────────────────

  {
    id: 'bulgariansplitsquat',
    name: 'Bulgarian Split Squat',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Calves'],
    difficulty: 'Intermediate',
    description: 'The king of unilateral leg exercises. Rear foot elevated, front foot bears the load — brutal quad and glute builder.',
    cues: [
      'Rear foot elevated on a bench or chair, laces down',
      'Front foot far enough forward that the shin stays near-vertical at the bottom',
      'Lower until the rear knee nearly touches the floor',
      'Drive through your front heel to stand — keep torso upright',
      'Don\'t let your front knee cave inward — press it out over your toe',
    ],
    riskNote: 'High knee demand on the front leg. AI monitors front knee valgus and torso lean carefully.',
    isNew: true,
  },
  {
    id: 'glutebridge',
    name: 'Glute Bridge',
    muscles: ['Glutes', 'Hamstrings', 'Core', 'Lower Back'],
    difficulty: 'Beginner',
    description: 'A supine hip thrust variation. Activates the glutes without spinal loading — perfect for warm-up or rehab.',
    cues: [
      'Lie on your back, knees bent, feet flat and hip-width',
      'Drive your hips up by squeezing your glutes hard',
      'At the top: thighs, torso, and calves form a straight line',
      'Hold 1-2 seconds at the top — really squeeze',
      'Lower with control — don\'t drop your hips',
    ],
    riskNote: 'Very low injury risk. AI monitors hip height symmetry.',
    isNew: true,
  },
  {
    id: 'hipthrust',
    name: 'Hip Thrust',
    muscles: ['Glutes', 'Hamstrings', 'Core'],
    difficulty: 'Intermediate',
    description: 'Shoulders on a bench, hips driving up. The most direct glute-loading movement available without a machine.',
    cues: [
      'Upper back rests on the bench — shoulder blades on the edge',
      'Feet flat, hip-width, knees at 90° at the top of the movement',
      'Drive hips up explosively, squeeze glutes hard at lockout',
      'Keep chin tucked — no neck hyperextension at the top',
      'Lower with control — feel the stretch in your hip flexors',
    ],
    riskNote: 'Lower back stress if you hyperextend at the top. AI monitors spine alignment and hip height.',
    isNew: true,
  },
  {
    id: 'donkeykick',
    name: 'Donkey Kick',
    muscles: ['Glutes', 'Hamstrings', 'Core'],
    difficulty: 'Beginner',
    description: 'On all fours, kick one leg back and up. Isolates the glute in hip extension — great activation work.',
    cues: [
      'Start on hands and knees — wrists under shoulders, knees under hips',
      'Keeping the knee bent at 90°, drive your heel toward the ceiling',
      'Squeeze your glute hard at the top — don\'t hyperextend your lower back',
      'Keep hips level — no rotation toward the kicking side',
      'Control the lowering phase — don\'t just drop',
    ],
    riskNote: 'Very low injury risk. AI monitors hip rotation and lower back position.',
    isNew: true,
  },
  {
    id: 'firehydrant',
    name: 'Fire Hydrant',
    muscles: ['Glutes', 'Hip Abductors', 'Core'],
    difficulty: 'Beginner',
    description: 'On all fours, lift one knee out to the side. Targets glute medius — critical for hip stability and knee health.',
    cues: [
      'Start on hands and knees — neutral spine',
      'Keeping knee bent, lift one leg out to the side like a dog at a fire hydrant',
      'Drive your knee up until your thigh is parallel to the floor',
      'Keep hips square — resist the urge to tilt toward the working leg',
      'Hold 1 second at the top, then lower with control',
    ],
    riskNote: 'Very low injury risk. AI watches hip tilt and symmetry.',
    isNew: true,
  },
  {
    id: 'reverseLunge',
    name: 'Reverse Lunge',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    difficulty: 'Beginner',
    description: 'Step backward rather than forward. Less forward knee stress than a forward lunge — great for beginners or knee issues.',
    cues: [
      'Step backward, landing on the ball of your foot',
      'Lower your back knee toward the floor — keep front shin vertical',
      'Keep your torso upright — don\'t lean forward',
      'Drive through the front heel to return to standing',
      'Keep front knee tracking over your second toe',
    ],
    riskNote: 'Lower knee stress than forward lunge. AI monitors front knee valgus and torso lean.',
    isNew: true,
  },
  {
    id: 'curtsylunge',
    name: 'Curtsy Lunge',
    muscles: ['Glutes', 'Quads', 'Adductors'],
    difficulty: 'Intermediate',
    description: 'Step behind and across your body. Hits glute medius and adductors in a unique diagonal pattern.',
    cues: [
      'Step one foot behind and across your body, like a curtsy',
      'Lower your back knee toward the floor',
      'Keep your front knee tracking over your front toe — not caving in',
      'Keep your torso upright throughout',
      'Drive through your front heel to return',
    ],
    riskNote: 'Unusual lateral stress on front knee. AI monitors front knee valgus carefully.',
    isNew: true,
  },
  {
    id: 'sumoSquat',
    name: 'Sumo Squat',
    muscles: ['Adductors', 'Glutes', 'Quads', 'Inner Thighs'],
    difficulty: 'Beginner',
    description: 'Wide stance, toes pointed out. Emphasizes the adductors and glutes more than a standard squat.',
    cues: [
      'Take a wide stance — roughly 1.5–2x shoulder width, toes pointed out 45°',
      'Squat down between your legs — knees tracking over toes',
      'Keep chest tall and torso upright',
      'Drive through your heels to stand, squeezing glutes at the top',
      'Don\'t let knees cave inward — push them out actively',
    ],
    riskNote: 'More adductor stress than standard squat. AI tracks knee valgus and hip depth.',
    isNew: true,
  },
  {
    id: 'stepup',
    name: 'Step-Up',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Calves'],
    difficulty: 'Beginner',
    description: 'Step up onto a box or bench. Unilateral leg exercise that builds functional strength and balance.',
    cues: [
      'Place your whole foot on the step — no heel hanging off the edge',
      'Drive through your front heel to step up — don\'t push off the back foot',
      'Stand fully upright at the top before stepping down',
      'Step down with control — land softly on the trailing foot',
      'Keep your front knee tracking over your toe throughout',
    ],
    riskNote: 'AI monitors knee valgus on the stepping leg and torso lean.',
    isNew: true,
  },
  {
    id: 'nordicCurl',
    name: 'Nordic Curl',
    muscles: ['Hamstrings', 'Glutes', 'Core'],
    difficulty: 'Advanced',
    description: 'Kneel and lower your torso forward against hamstring resistance. The most effective hamstring injury prevention exercise known to science.',
    cues: [
      'Kneel on a soft surface, feet anchored under a fixed object',
      'Keeping your body rigid, lower yourself forward slowly — 3-5 seconds down',
      'Control the descent as long as possible, catch yourself with your hands at the end',
      'Push back up to the start position',
      'This is extremely difficult — build up from 3-5 reps maximum',
    ],
    riskNote: 'Very high hamstring stress — do not rush progression. AI monitors torso rigidity and pace.',
    isNew: true,
  },

  // ── Core ───────────────────────────────────────────────────────────────

  {
    id: 'sideplank',
    name: 'Side Plank',
    muscles: ['Obliques', 'Core', 'Glutes', 'Shoulders'],
    difficulty: 'Intermediate',
    isHold: true,
    description: 'A lateral isometric hold that targets the obliques and builds frontal plane stability.',
    cues: [
      'Stack feet on top of each other, forearm under shoulder',
      'Hips lifted high — body forms a straight diagonal line',
      'Do not let hips sag or pike — keep them in line with shoulders and feet',
      'Look straight ahead — neutral neck',
      'Breathe steadily — don\'t hold your breath',
    ],
    riskNote: 'AI monitors hip height — sag indicates oblique fatigue.',
    isNew: true,
  },
  {
    id: 'deadbug',
    name: 'Dead Bug',
    muscles: ['Core', 'Hip Flexors', 'Abs'],
    difficulty: 'Beginner',
    description: 'Lying on your back, extend opposite arm and leg. The gold-standard anti-extension core exercise.',
    cues: [
      'Lie on your back, arms straight up, knees bent at 90° over hips',
      'Press your lower back firmly into the floor — this must not change',
      'Slowly lower one arm overhead while extending the opposite leg — stop before the back lifts',
      'Return to start and repeat on the other side',
      'Breathe out as you extend — this helps flatten the back',
    ],
    riskNote: 'Very low injury risk. AI monitors lower back position — the key is that it never leaves the floor.',
    isHold: true,
    isNew: true,
  },
  {
    id: 'birddog',
    name: 'Bird Dog',
    muscles: ['Core', 'Lower Back', 'Glutes', 'Shoulders'],
    difficulty: 'Beginner',
    description: 'On all fours, extend opposite arm and leg. Classic spinal stability and coordination exercise.',
    cues: [
      'Start on hands and knees — neutral spine, no sagging or arching',
      'Extend one arm forward and the opposite leg back simultaneously',
      'Hold 2-3 seconds — body from hand to heel forms one straight line',
      'Return and switch sides without touching the floor with knee or hand first',
      'Do not let the hip on the extended leg side hike up or rotate',
    ],
    riskNote: 'Very low injury risk. AI monitors hip rotation and spine alignment.',
    isHold: true,
    isNew: true,
  },
  {
    id: 'russiantwist',
    name: 'Russian Twist',
    muscles: ['Obliques', 'Core', 'Hip Flexors'],
    difficulty: 'Intermediate',
    description: 'A seated rotation exercise targeting the obliques. Adds a rotational demand that planks and crunches miss.',
    cues: [
      'Sit at 45° lean, knees bent, feet lifted off floor (or heels on floor for easier version)',
      'Clasp hands at chest, twist your torso left and right',
      'Lead with your shoulders, not just your arms',
      'Keep your chest tall — don\'t collapse your spine',
      'Move with control — this is not a speed exercise',
    ],
    riskNote: 'Spinal rotation under load requires a healthy disc. AI monitors torso position and symmetry.',
    isNew: true,
  },
  {
    id: 'bicycleCrunch',
    name: 'Bicycle Crunch',
    muscles: ['Obliques', 'Abs', 'Hip Flexors'],
    difficulty: 'Intermediate',
    description: 'Lying rotation crunch. One of the highest-activation abdominal exercises in EMG research.',
    cues: [
      'Lie on your back, hands lightly behind head',
      'Alternate touching elbow to opposite knee in a cycling motion',
      'Fully extend the non-active leg — don\'t keep both knees bent',
      'Rotate from the torso — don\'t just pull your head side to side',
      'Slow and controlled beats fast and sloppy every time',
    ],
    riskNote: 'Neck strain risk. AI monitors head pull and rotation quality.',
    isNew: true,
  },
  {
    id: 'legRaise',
    name: 'Leg Raise',
    muscles: ['Abs', 'Hip Flexors', 'Core'],
    difficulty: 'Intermediate',
    description: 'Lying leg raise to vertical. Works the lower abdominals and hip flexors through a long range of motion.',
    cues: [
      'Lie flat, hands palms-down under your lower back for support',
      'Keep legs straight, raise them to 90° with the floor',
      'Lower slowly — stop 2-3 inches off the floor, don\'t rest between reps',
      'Press your lower back into the floor throughout',
      'If lower back arches, bend knees slightly',
    ],
    riskNote: 'Lower back risk if spine lifts off the floor. AI monitors hip flexor pull on the lumbar spine.',
    isNew: true,
  },
  {
    id: 'flutterKick',
    name: 'Flutter Kicks',
    muscles: ['Abs', 'Hip Flexors', 'Quads'],
    difficulty: 'Intermediate',
    description: 'Small alternating leg kicks just above the floor. Sustained hip flexor and lower ab endurance.',
    cues: [
      'Lie flat, hands under your lower back or glutes for support',
      'Lift both legs 6 inches off the floor',
      'Alternate kicking up and down in small quick motions',
      'Keep legs as straight as possible',
      'Keep lower back pressed into the floor throughout',
    ],
    riskNote: 'Same lower back risk as leg raises. AI monitors spine arch.',
    isNew: true,
  },
  {
    id: 'hollowbody',
    name: 'Hollow Body Hold',
    muscles: ['Core', 'Abs', 'Hip Flexors'],
    difficulty: 'Intermediate',
    isHold: true,
    description: 'The foundation of gymnastics strength. A full-body tension position that builds deep core control.',
    cues: [
      'Lie on your back, press your lower back completely into the floor',
      'Arms overhead, legs extended — lift both slightly off the floor',
      'Body forms a curved "banana" shape — lower back stays flat',
      'Press arms toward ears and squeeze everything — abs, glutes, quads',
      'If back lifts, raise legs higher or bend knees',
    ],
    riskNote: 'Core demands are high. AI monitors lower back — it must stay pressed down.',
    isNew: true,
  },
  {
    id: 'vSit',
    name: 'V-Sit',
    muscles: ['Abs', 'Hip Flexors', 'Core'],
    difficulty: 'Advanced',
    isHold: true,
    description: 'Sit on your tailbone balancing with legs and torso forming a V. Extreme core compression strength.',
    cues: [
      'Sit on the floor, lean back slightly, and lift legs to 45°',
      'Arms extended forward parallel to the floor for balance',
      'Hold the position — keep spine tall, not rounded',
      'Breathe steadily — resist collapsing the chest',
      'Tuck and extend legs to make easier/harder',
    ],
    riskNote: 'High hip flexor and spinal compression demand. AI monitors spine and leg angle.',
    isNew: true,
  },

  // ── Cardio / HIIT ──────────────────────────────────────────────────────

  {
    id: 'boxjump',
    name: 'Box Jump',
    muscles: ['Quads', 'Glutes', 'Calves', 'Core'],
    difficulty: 'Advanced',
    description: 'Explosive jump onto a box. The primary plyometric lower-body power movement.',
    cues: [
      'Stand close to the box — 1 foot away',
      'Dip into a quarter squat, swing arms back',
      'Explode up and forward — drive arms forward as you jump',
      'Land softly on the box — full foot, knees bent, absorb impact',
      'Stand fully upright on the box before stepping down',
    ],
    riskNote: 'High ACL risk on landing if knees cave. AI watches landing mechanics closely.',
    isNew: true,
  },
  {
    id: 'skaterjump',
    name: 'Skater Jump',
    muscles: ['Glutes', 'Quads', 'Adductors', 'Core', 'Calves'],
    difficulty: 'Intermediate',
    description: 'Lateral bounding movement mimicking a speed skater. Builds single-leg power and lateral stability.',
    cues: [
      'Leap laterally from one foot to the other',
      'Land on the outer foot, swinging the free leg behind',
      'Load into the landing — don\'t just touch and go',
      'Reach the opposite hand toward the landing foot for balance',
      'Build the width of your bound over time',
    ],
    riskNote: 'Single-leg landing impact. AI tracks landing mechanics and knee position.',
    isNew: true,
  },
  {
    id: 'tuckjump',
    name: 'Tuck Jump',
    muscles: ['Quads', 'Calves', 'Core', 'Glutes'],
    difficulty: 'Advanced',
    description: 'Jump and pull your knees to your chest at peak height. Maximum power output in a compact movement.',
    cues: [
      'Dip and explode upward with maximum effort',
      'At peak height, drive knees toward your chest',
      'Land softly — hips and knees bend to absorb',
      'Immediately reload into the next jump',
      'Arms pump down as legs tuck up — coordinate the countermovement',
    ],
    riskNote: 'Highest plyometric impact in this library. AI monitors landing mechanics and knee control.',
    isNew: true,
  },
  {
    id: 'starjump',
    name: 'Star Jump',
    muscles: ['Full Body', 'Cardio', 'Glutes', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'An explosive jumping jack variation with a full arm and leg extension at peak height.',
    cues: [
      'Start in a partial squat, arms tucked in',
      'Explode up and out — arms and legs spread wide to form a star shape at peak height',
      'Land with feet together, knees soft',
      'Return immediately to the squat position for the next rep',
      'Keep the rhythm — this is a cardio movement',
    ],
    riskNote: 'Landing mechanics matter. AI monitors knee valgus on each landing.',
    isNew: true,
  },
  {
    id: 'broadjump',
    name: 'Broad Jump',
    muscles: ['Quads', 'Glutes', 'Calves', 'Core'],
    difficulty: 'Intermediate',
    description: 'Maximum horizontal jump. A classic test of lower-body explosive power.',
    cues: [
      'Start with feet shoulder-width, half squat position',
      'Swing arms back, then explosively forward as you jump',
      'Extend fully through your hips, knees, and ankles at takeoff',
      'Land on both feet simultaneously, absorbing impact with a squat',
      'Aim to land balanced — no falling forward or backward',
    ],
    riskNote: 'Ankle and knee stress on landing. AI tracks landing mechanics.',
    isNew: true,
  },
  {
    id: 'shadowboxing',
    name: 'Shadow Boxing',
    muscles: ['Shoulders', 'Core', 'Cardio', 'Upper Back'],
    difficulty: 'Beginner',
    description: 'Punch combinations in the air at boxing speed. Excellent shoulder endurance and cardio conditioning.',
    cues: [
      'Athletic stance: one foot forward, hands at chin level',
      'Rotate from the torso — power comes from hips, not just arms',
      'Keep your guard up between combinations — hands return to chin',
      'Stay light on your feet — use small steps and pivots',
      'Breathe rhythmically — exhale sharply on each punch',
    ],
    riskNote: 'Low injury risk. AI monitors arm symmetry and shoulder height throughout.',
    isNew: true,
  },

  // ── Stretching / Mobility ──────────────────────────────────────────────

  {
    id: 'catcow',
    name: 'Cat-Cow',
    muscles: ['Spine', 'Lower Back', 'Core', 'Neck'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'A gentle spinal flexion-extension mobilization. Warms up every segment of the spine — essential before any workout.',
    cues: [
      'Start on hands and knees, spine neutral',
      'Cow: inhale, drop your belly, lift your head and tailbone (arch)',
      'Cat: exhale, round your spine toward the ceiling, tuck chin and tailbone',
      'Move slowly and deliberately — explore your full range',
      '10–15 cycles minimum for a proper warm-up effect',
    ],
    riskNote: 'Extremely low injury risk. AI monitors the completeness of both flexion and extension.',
    isNew: true,
  },
  {
    id: 'childpose',
    name: 'Child\'s Pose',
    muscles: ['Lower Back', 'Hip Flexors', 'Lats', 'Glutes'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'A full body rest and reset position. Decompresses the lower back and stretches the lats and hips.',
    cues: [
      'Kneel with knees wide, big toes touching',
      'Sit back toward your heels as far as comfortable',
      'Stretch arms forward on the floor — reach as long as possible',
      'Let your chest and forehead drop toward the floor',
      'Breathe deeply — each exhale deepens the stretch',
    ],
    riskNote: 'Very low injury risk. AI watches for full arm extension and hips-to-heels depth.',
    isNew: true,
  },
  {
    id: 'worldsgreateststretch',
    name: 'World\'s Greatest Stretch',
    muscles: ['Hip Flexors', 'Thoracic Spine', 'Hamstrings', 'Groin'],
    difficulty: 'Beginner',
    description: 'A compound stretch hitting the entire body in one movement. The single best warm-up stretch known.',
    cues: [
      'Start in a lunge position — front foot flat, back knee on floor',
      'Place the same-side hand as front foot flat on the floor inside the front foot',
      'Rotate your opposite arm up to the sky, following with your eyes',
      'Hold 2 seconds at the top of the rotation, then switch sides',
      'Do 5 reps each side as part of your warm-up',
    ],
    riskNote: 'Very low injury risk. AI tracks thoracic rotation depth and hip alignment.',
    isHold: true,
    isNew: true,
  },
  {
    id: 'hipflexorstretch',
    name: 'Hip Flexor Stretch',
    muscles: ['Hip Flexors', 'Quads', 'Psoas'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'A deep lunge stretch targeting the psoas and hip flexors — the most commonly tight muscles for desk workers.',
    cues: [
      'Kneel on one knee — the stretching leg is behind you',
      'Shift forward until you feel a deep stretch in the front of the rear hip',
      'Keep your torso upright — don\'t lean forward',
      'Squeeze the glute of the rear leg to intensify the stretch',
      'Hold 30-60 seconds each side',
    ],
    riskNote: 'Very low injury risk. AI monitors torso angle and rear hip position.',
    isNew: true,
  },
  {
    id: 'hamstringstretch',
    name: 'Standing Hamstring Stretch',
    muscles: ['Hamstrings', 'Lower Back', 'Calves'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'Bend forward from the hips to stretch the posterior chain. Essential after any leg session.',
    cues: [
      'Stand with feet hip-width, soft bend in the knees',
      'Hinge from your hips — not your waist — letting your torso hang toward the floor',
      'Let your arms hang or grip your shins for a deeper pull',
      'Hold 30-45 seconds, breathing steadily',
      'Don\'t force it — the stretch should be felt behind the thighs, not in the lower back',
    ],
    riskNote: 'Very low injury risk. AI monitors spine position — avoid rounding excessively.',
    isNew: true,
  },
  {
    id: 'quadstretch',
    name: 'Standing Quad Stretch',
    muscles: ['Quadriceps', 'Hip Flexors'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'Pull your heel to your glute. The basic quad stretch — important after knee-intensive sessions.',
    cues: [
      'Stand on one foot — hold a wall or chair if needed for balance',
      'Bend the other knee, bringing the heel toward your glute',
      'Grip the ankle (not the foot) and hold',
      'Keep your knees together — don\'t let the bent knee drift out',
      'Hold 30 seconds each side',
    ],
    riskNote: 'Very low injury risk. AI monitors standing leg stability and knee alignment.',
    isNew: true,
  },
  {
    id: 'pigeonpose',
    name: 'Pigeon Pose',
    muscles: ['Glutes', 'Hip External Rotators', 'Hip Flexors'],
    difficulty: 'Intermediate',
    isHold: true,
    description: 'A deep hip opener from yoga. Targets the glute medius and piriformis — key muscles for hip and knee health.',
    cues: [
      'From all fours, bring one knee forward and place it behind your wrist',
      'Extend the other leg straight back — hips square to the floor',
      'Lower your torso toward the floor, arms extended forward',
      'Breathe into the stretch — each exhale deepens the hip opening',
      'Hold 45-90 seconds per side',
    ],
    riskNote: 'Significant hip stress. AI monitors hip alignment and torso position.',
    isNew: true,
  },
  {
    id: 'downdogstretch',
    name: 'Downward Dog',
    muscles: ['Hamstrings', 'Calves', 'Shoulders', 'Lats', 'Spine'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'An inverted V yoga pose that simultaneously stretches the entire posterior chain and opens the shoulders.',
    cues: [
      'Start in a plank and push hips up and back to form an inverted V',
      'Straighten your legs as much as possible — heels pressing toward the floor',
      'Press your hands into the floor and rotate arms outward',
      'Let your head hang between your arms — no tension in the neck',
      'Hold 30-60 seconds and pedal your heels for a deeper calf stretch',
    ],
    riskNote: 'AI monitors shoulder symmetry and spine length in the inverted position.',
    isNew: true,
  },
  {
    id: 'cobrapose',
    name: 'Cobra Pose',
    muscles: ['Spine', 'Lower Back', 'Chest', 'Shoulders'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'Lying face down, press up through your hands to arch the spine. Counteracts forward flexion from sitting and core work.',
    cues: [
      'Lie face down, hands flat under your shoulders',
      'Press up slowly, lifting chest off the floor — only as high as feels comfortable',
      'Keep hips on the floor — this is not a push-up',
      'Shoulders down and away from your ears',
      'Hold 20-30 seconds, breathe into the stretch',
    ],
    riskNote: 'Avoid if you have a herniated disc. AI monitors shoulder shrug and hip lift.',
    isNew: true,
  },
  {
    id: 'seatedspinaltwist',
    name: 'Seated Spinal Twist',
    muscles: ['Spine', 'Obliques', 'Glutes', 'Lower Back'],
    difficulty: 'Beginner',
    isHold: true,
    description: 'Seated rotation stretch for thoracic and lumbar mobility. Restores spinal rotation range of motion.',
    cues: [
      'Sit tall on the floor, legs extended',
      'Bend one knee and cross it over the other leg',
      'Twist toward the bent knee, placing your opposite elbow on the outside of the knee',
      'Look over your shoulder in the direction of the twist',
      'Hold 30 seconds each side, breathing steadily',
    ],
    riskNote: 'Very low injury risk. AI monitors torso upright position and rotation depth.',
    isNew: true,
  },
  {
    id: 'anklecircle',
    name: 'Ankle Circles',
    muscles: ['Ankles', 'Calves', 'Lower Leg'],
    difficulty: 'Beginner',
    description: 'Rotate the ankle through its full range of motion. Essential warm-up before any running or jumping activity.',
    cues: [
      'Sit or stand, lift one foot off the floor',
      'Rotate the foot in large circles — clockwise and counterclockwise',
      'Make the circles as big as your ankle allows',
      'Do 10 circles each direction on each foot',
      'Slow and deliberate beats fast',
    ],
    riskNote: 'No injury risk. AI monitors range of motion symmetry between left and right.',
    isHold: true,
    isNew: true,
  },
  {
    id: 'neckroll',
    name: 'Neck Rolls',
    muscles: ['Neck', 'Cervical Spine', 'Upper Traps'],
    difficulty: 'Beginner',
    description: 'Gentle neck mobility circles. Releases tension and restores range of motion in the cervical spine.',
    cues: [
      'Sit or stand tall, relax your shoulders',
      'Drop one ear toward your shoulder, then roll forward through the full circle',
      'Move slowly — feel the stretch as you pass through each position',
      'Never roll your head back forcefully — stop at neutral',
      '5 circles each direction is sufficient',
    ],
    riskNote: 'Avoid full backward neck circles. AI monitors movement speed — should be slow and controlled.',
    isHold: true,
    isNew: true,
  },
  {
    id: 'shoulderroll',
    name: 'Shoulder Rolls',
    muscles: ['Trapezius', 'Rotator Cuff', 'Neck'],
    difficulty: 'Beginner',
    description: 'Roll shoulders forward and backward through full range. Releases upper trap tension and prepares the shoulder joint.',
    cues: [
      'Stand tall, arms relaxed at your sides',
      'Roll both shoulders forward in large circles, then backward',
      'Exaggerate the range — really come up, back, and down',
      '10 forward and 10 backward each session',
      'Keep neck relaxed throughout',
    ],
    riskNote: 'No injury risk. AI monitors symmetry between left and right shoulders.',
    isNew: true,
  },
  {
    id: 'wristcircle',
    name: 'Wrist Circles',
    muscles: ['Wrists', 'Forearms'],
    difficulty: 'Beginner',
    description: 'Rotate the wrists through full range. Essential warm-up before push-up, plank, or pressing work.',
    cues: [
      'Extend arms forward, make fists',
      'Rotate wrists in large circles — clockwise and counterclockwise',
      'Go slowly — feel the full range',
      '10 circles each direction',
      'Follow with wrist flexor and extensor stretches',
    ],
    riskNote: 'No injury risk. AI monitors range of motion and arm symmetry.',
    isHold: true,
    isNew: true,
  },

  // ── Additional Strength ────────────────────────────────────────────────

  {
    id: 'gobletSquat',
    name: 'Goblet Squat',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core', 'Upper Back'],
    difficulty: 'Beginner',
    description: 'Hold a weight at chest height and squat. The best loaded squat for beginners — the weight counterbalances and cues perfect depth.',
    cues: [
      'Hold a dumbbell or kettlebell vertically at your chest, elbows pointing down',
      'Feet shoulder-width, toes slightly out',
      'Squat deep — elbows track between your knees at the bottom',
      'Keep the weight close to your body throughout',
      'Drive through your whole foot to stand',
    ],
    riskNote: 'Same knee risks as squat. AI monitors knee valgus and depth.',
    isNew: true,
  },
  {
    id: 'romaniandeadlift',
    name: 'Romanian Deadlift',
    muscles: ['Hamstrings', 'Glutes', 'Lower Back', 'Traps'],
    difficulty: 'Intermediate',
    description: 'A hip-hinge movement emphasizing hamstring stretch under load. The best posterior chain exercise for muscle building.',
    cues: [
      'Stand with feet hip-width, soft bend in the knees',
      'Hinge from the hips — push them back as you lower',
      'Lower the weight along your legs — feel the hamstring stretch',
      'Stop when you feel a strong stretch in the hamstrings, not when you lose neutral spine',
      'Drive hips forward to stand — squeeze glutes at lockout',
    ],
    riskNote: 'High hamstring and lower back stress. AI monitors spine neutrality and hip-hinge depth.',
    isNew: true,
  },
  {
    id: 'dumbbellrow',
    name: 'Dumbbell Row',
    muscles: ['Lats', 'Rhomboids', 'Rear Delts', 'Biceps'],
    difficulty: 'Beginner',
    description: 'Single-arm row with a dumbbell, supporting yourself on a bench. The best unilateral back builder.',
    cues: [
      'Support yourself with one hand and knee on a bench',
      'Other hand holds the dumbbell, arm hanging straight down',
      'Pull the dumbbell to your hip — lead with your elbow, not your hand',
      'Squeeze your back at the top — hold 1 second',
      'Lower with control — full arm extension at the bottom',
    ],
    riskNote: 'AI monitors shoulder symmetry and elbow path.',
    isNew: true,
  },
  {
    id: 'arnoldpress',
    name: 'Arnold Press',
    muscles: ['Shoulders', 'Triceps', 'Upper Chest'],
    difficulty: 'Intermediate',
    description: 'A shoulder press with a rotation. Named after Arnold Schwarzenegger — trains all three deltoid heads.',
    cues: [
      'Start with palms facing you, dumbbells at chin height',
      'As you press up, rotate palms forward so they face out at the top',
      'Reverse the rotation as you lower back to start',
      'The rotation should be smooth and controlled — not a quick flick',
      'Do not arch your lower back — brace your core throughout',
    ],
    riskNote: 'Rotational shoulder movement. AI monitors symmetric rotation and wrist alignment.',
    isNew: true,
  },
  {
    id: 'frontraise',
    name: 'Front Raise',
    muscles: ['Anterior Deltoid', 'Shoulders', 'Upper Chest'],
    difficulty: 'Beginner',
    description: 'Raise arms to shoulder height in front. Isolates the anterior deltoid — often neglected compared to lateral delts.',
    cues: [
      'Stand tall, arms at sides with slight elbow bend',
      'Raise both arms forward to shoulder height — thumbs pointing up',
      'No swinging or momentum — controlled lift',
      'Lower slowly — 2-3 second descent',
      'Keep shoulders down — no shrugging',
    ],
    riskNote: 'AI monitors arm symmetry and shoulder shrug.',
    isNew: true,
  },
  {
    id: 'reverseFly',
    name: 'Reverse Fly',
    muscles: ['Rear Deltoid', 'Rhomboids', 'Middle Trap'],
    difficulty: 'Beginner',
    description: 'Bent over, raise arms out to sides. Directly targets rear delts and mid-back — critical for posture and shoulder health.',
    cues: [
      'Hinge forward 45-90°, arms hanging, slight elbow bend',
      'Raise arms out to the sides — lead with elbows, not hands',
      'Squeeze shoulder blades together at the top',
      'Lower slowly — most people drop too fast',
      'Keep your core engaged — don\'t let your back round',
    ],
    riskNote: 'AI monitors arm symmetry and back position.',
    isNew: true,
  },
  {
    id: 'skullcrusher',
    name: 'Skull Crusher',
    muscles: ['Triceps', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'Lying tricep extension. Allows heavy loading of the triceps through a full range of motion.',
    cues: [
      'Lie on your back, arms extended straight up',
      'Bend elbows, lowering the weight toward your forehead (not past it)',
      'Keep upper arms completely vertical throughout — only lower arms move',
      'Press back to full extension, squeezing triceps',
      'Use a controlled weight — this is not a movement to ego-lift',
    ],
    riskNote: 'High elbow and wrist stress with heavy weight. AI monitors elbow angle and wrist alignment.',
    isNew: true,
  },
  {
    id: 'concentrationcurl',
    name: 'Concentration Curl',
    muscles: ['Biceps', 'Brachialis'],
    difficulty: 'Beginner',
    description: 'Seated, elbow braced against inner thigh. Maximum isolation for the bicep — eliminating all body sway.',
    cues: [
      'Sit on bench, lean forward, brace the upper arm of the curling side against your inner thigh',
      'Curl the weight from full extension to full contraction — slow and deliberate',
      'Squeeze at the top for 1-2 seconds',
      'Lower with control — don\'t let it drop',
      'Do not swing your torso or shrug at the top',
    ],
    riskNote: 'AI monitors elbow position and prevents shoulder compensation.',
    isNew: true,
  },
  {
    id: 'zottmancurl',
    name: 'Zottman Curl',
    muscles: ['Biceps', 'Brachialis', 'Brachioradialis', 'Forearms'],
    difficulty: 'Intermediate',
    description: 'A bicep curl that changes grip at the top. The most effective curl for hitting all elbow flexors in one movement.',
    cues: [
      'Curl up with a supinated grip (palms up) — normal bicep curl',
      'At the top, rotate to a pronated grip (palms down)',
      'Lower with the pronated grip — this is the hardest part',
      'Rotate back to supinated at the bottom',
      'Keep elbows pinned to your sides throughout',
    ],
    riskNote: 'Grip rotation places unique stress on the forearm. AI monitors elbow stability.',
    isNew: true,
  },
  {
    id: 'wristcurl',
    name: 'Wrist Curl',
    muscles: ['Forearms', 'Wrist Flexors', 'Grip Strength'],
    difficulty: 'Beginner',
    description: 'Seated forearm curl. Directly trains wrist flexors and grip strength — often the limiting factor in pulling movements.',
    cues: [
      'Sit, rest forearms on thighs with palms facing up, wrists at the edge of your knees',
      'Lower the weight by extending the wrist as far as comfortable',
      'Curl the weight up by flexing the wrist — squeeze at the top',
      'Keep forearms flat on thighs — only the wrists move',
      'Use light weight — forearms are a small muscle group',
    ],
    riskNote: 'Can aggravate carpal tunnel. AI monitors wrist range of motion and symmetry.',
    isHold: true,
    isNew: true,
  },
  {
    id: 'goodmorning',
    name: 'Good Morning',
    muscles: ['Hamstrings', 'Lower Back', 'Glutes', 'Core'],
    difficulty: 'Intermediate',
    description: 'Bar on back, hinge forward at the hips. A direct hip-hinge builder with a unique hamstring stretch under load.',
    cues: [
      'Stand with bar on upper back (or arms crossed at chest for bodyweight version)',
      'Hip-width stance, soft knee bend',
      'Hinge from the hips — push them back while keeping a flat back',
      'Lower until you feel a strong hamstring stretch — stop there',
      'Drive hips forward to return to standing',
    ],
    riskNote: 'Significant lower back stress. Never round the spine under load. AI monitors spinal alignment closely.',
    isNew: true,
  },
  {
    id: 'hyperextension',
    name: 'Back Extension',
    muscles: ['Lower Back', 'Glutes', 'Hamstrings'],
    difficulty: 'Intermediate',
    description: 'Hip-hinge extension against gravity. Directly strengthens the erector spinae and lower back.',
    cues: [
      'Lie face down over a hyperextension bench or Roman chair, hips at the pad edge',
      'Hands crossed on chest or behind head',
      'Lower torso toward the floor with control',
      'Drive back up to neutral — do not hyperextend past the hips',
      'Squeeze glutes at the top rather than arching your lower back',
    ],
    riskNote: 'Hyperextending past parallel compresses the lumbar spine. AI monitors peak extension angle.',
    isNew: true,
  },
  {
    id: 'abWheel',
    name: 'Ab Wheel Rollout',
    muscles: ['Core', 'Abs', 'Lats', 'Shoulders'],
    difficulty: 'Advanced',
    description: 'Roll an ab wheel forward from your knees. One of the hardest anti-extension core exercises available.',
    cues: [
      'Kneel on a mat, grip the ab wheel handles',
      'Roll forward slowly — body extends toward the floor',
      'Keep your core braced — lower back must not arch',
      'Roll out as far as you can maintain a flat back',
      'Pull back to kneeling using your core and lats — not momentum',
    ],
    riskNote: 'Lower back injury risk if the core is not strong enough. Start with partial rollouts. AI monitors lumbar arch.',
    isNew: true,
  },
]

export interface WorkoutProgram {
  id: string
  name: string
  description: string
  level: 'Beginner' | 'Intermediate' | 'Advanced'
  duration: string
  exercises: string[]
  tags: string[]
  emoji: string
  targetReps: number     // reps to complete before auto-advancing to next exercise
  targetHoldSecs: number // seconds for hold exercises (plank, wallsit, etc.)
}

export const WORKOUT_PROGRAMS: WorkoutProgram[] = [
  {
    id: 'beginner-full-body',
    name: 'Beginner Full Body',
    description: 'A complete intro routine hitting every major muscle group. Perfect for your first week.',
    level: 'Beginner',
    duration: '~20 min',
    exercises: ['squat', 'pushup', 'lunge', 'curlup'],
    tags: ['Full Body', 'No Equipment', 'Strength'],
    emoji: '🌱',
    targetReps: 10,
    targetHoldSecs: 30,
  },
  {
    id: 'upper-body-burn',
    name: 'Upper Body Burn',
    description: 'Chest, shoulders, arms. Three pushing exercises back to back for an upper-body pump.',
    level: 'Intermediate',
    duration: '~20 min',
    exercises: ['pushup', 'shoulderpress', 'bicepcurl', 'tricepextension'],
    tags: ['Upper Body', 'Push', 'Strength'],
    emoji: '💪',
    targetReps: 12,
    targetHoldSecs: 30,
  },
  {
    id: 'lower-body-power',
    name: 'Lower Body Power',
    description: 'Quads, glutes, hamstrings. Heavy compound movements for leg strength and power.',
    level: 'Intermediate',
    duration: '~25 min',
    exercises: ['squat', 'deadlift', 'lunge'],
    tags: ['Lower Body', 'Strength', 'Power'],
    emoji: '🦵',
    targetReps: 10,
    targetHoldSecs: 30,
  },
  {
    id: 'hiit-circuit',
    name: 'HIIT Circuit',
    description: 'Alternating cardio and strength bursts. Max heart rate, minimum rest.',
    level: 'Intermediate',
    duration: '~15 min',
    exercises: ['jumpingjack', 'squat', 'highnees', 'pushup'],
    tags: ['Cardio', 'HIIT', 'Full Body'],
    emoji: '⚡',
    targetReps: 20,
    targetHoldSecs: 30,
  },
  {
    id: 'core-stability',
    name: 'Core & Stability',
    description: 'Isometric holds and controlled movements that build deep core strength and posture.',
    level: 'Beginner',
    duration: '~15 min',
    exercises: ['plank', 'wallsit', 'curlup'],
    tags: ['Core', 'Stability', 'Isometric'],
    emoji: '🎯',
    targetReps: 10,
    targetHoldSecs: 30,
  },
  {
    id: 'strength-builder',
    name: 'Strength Builder',
    description: 'Compound push, pull, and leg movements. The full-body strength standard.',
    level: 'Advanced',
    duration: '~35 min',
    exercises: ['deadlift', 'squat', 'pullup', 'pushup', 'shoulderpress', 'lunge'],
    tags: ['Full Body', 'Compound', 'Strength'],
    emoji: '🏋️',
    targetReps: 10,
    targetHoldSecs: 30,
  },
  {
    id: 'arms-shoulders',
    name: 'Arms & Shoulders',
    description: 'A complete arm and shoulder isolation routine covering all major push and pull muscles.',
    level: 'Intermediate',
    duration: '~25 min',
    exercises: ['bicepcurl', 'hammercurl', 'tricepextension', 'lateralraise', 'shoulderpress'],
    tags: ['Upper Body', 'Isolation', 'Arms'],
    emoji: '💪',
    targetReps: 12,
    targetHoldSecs: 30,
  },
]

export interface ActiveProgram {
  id: string
  name: string
  exercises: string[]
  currentIndex: number
  targetReps: number
  targetHoldSecs: number
}

export const PROGRAM_KEY = 'formAI_activeProgram'

export function getActiveProgram(): ActiveProgram | null {
  try {
    const raw = localStorage.getItem(PROGRAM_KEY)
    if (!raw) return null
    return JSON.parse(raw) as ActiveProgram
  } catch {
    return null
  }
}

export function setActiveProgram(program: WorkoutProgram): void {
  const active: ActiveProgram = {
    id: program.id,
    name: program.name,
    exercises: program.exercises,
    currentIndex: 0,
    targetReps: program.targetReps,
    targetHoldSecs: program.targetHoldSecs,
  }
  localStorage.setItem(PROGRAM_KEY, JSON.stringify(active))
}

export function advanceProgramExercise(): ActiveProgram | null {
  const current = getActiveProgram()
  if (!current) return null
  const next = { ...current, currentIndex: current.currentIndex + 1 }
  if (next.currentIndex >= next.exercises.length) {
    localStorage.removeItem(PROGRAM_KEY)
    return null
  }
  localStorage.setItem(PROGRAM_KEY, JSON.stringify(next))
  return next
}

export function clearActiveProgram(): void {
  localStorage.removeItem(PROGRAM_KEY)
}

// ── Custom programs (user-created / AI-generated) ──────────────────────────

const CUSTOM_PROGRAMS_KEY = 'formAI_custom_programs'

export function getCustomPrograms(): WorkoutProgram[] {
  try {
    const raw = localStorage.getItem(CUSTOM_PROGRAMS_KEY)
    return raw ? (JSON.parse(raw) as WorkoutProgram[]) : []
  } catch { return [] }
}

export function saveCustomProgram(program: WorkoutProgram): void {
  const existing = getCustomPrograms().filter(p => p.id !== program.id)
  localStorage.setItem(CUSTOM_PROGRAMS_KEY, JSON.stringify([program, ...existing]))
}

export function deleteCustomProgram(id: string): void {
  const programs = getCustomPrograms().filter(p => p.id !== id)
  localStorage.setItem(CUSTOM_PROGRAMS_KEY, JSON.stringify(programs))
}
